project:
  type: book
  output-dir: book

book:
  title: "Програмування на C#"
  subtitle: "Навчальний посібник з курсу **Програмування на `C#`** для студентів спеціальності 121 Комп'ютерні науки та 051 Економічна кібернетика, 1-3 курс"
  author: "Юрій Клебан"
  date: "28/12/2024"
  google-analytics: ""
  cover-image: img/cover.png
  site-url: https://kleban.page/csharp-book/
  repo-url: https://github.com/kleban/csharp-book/
  repo-branch: main
  sharing: [twitter, facebook, linkedin]
  favicon: img/favicon.png
  chapters:
    - index.qmd
    - part: "Частина 1. Основи алгоритмізації та програмування"
      chapters:
        - lecture-1.qmd
        - lecture-2.qmd
        - lecture-2_4.qmd
        - lecture-3.qmd
        - lecture-4.qmd
        - lecture-5.qmd
        - lecture-6.qmd
    - part: "Частина 2. Основи ООП"
    - part: "Частина 3. Робота з даними"
    - part: "Частина 4. Веб-розробка з ASP.NET MVC"
      chapters:
        - lecture-asp-net-mvc-to-do.qmd
        - lecture-expense-manager-asp-net.qmd
    - part: "Частина Х. Додаткові теми"
      chapters:
        - lecture-x1.qmd
  page-navigation: true
  page-footer: "Copyright 2025, Юрій Клебан" 

language: _language-ua.yml 

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: img/cover.png
    code-link: true
    css: css/style.css
    number-sections: false
    toc: true
    highlight-style: github
    code-line-numbers: true

crossref:
  tbl-title: 'Таблиця'
  lst-title: 'Лістинг'
  fig-title: 'Рис.'
  fig-labels: arabic
  title-delim: "."

editor: visual

