---
title: 1.1. Загальні категорії та поняття програмування
keywords: програмування, алгоритм, мова програмування, програма, програмне забезпечення, розробка, блок-схеми, інформатика, додатки, задачі
description: "Дізнайтеся базові поняття програмування: алгоритми, мови програмування, програми та програмне забезпечення. Розкриємо суть розробки програмного забезпечення, ключових етапів створення програм і застосування алгоритмів у вирішенні задач."
author: "Юрій Клебан"
date: "28/12/2024"
date-format: short
---

::: {.callout-note}
Презентація до заняття:

<iframe src="https://1drv.ms/p/c/0a1340ba71b3f0aa/IQSq8LNxukATIIAKhBEAAAAAAchpo89BCfNqnG5fWpmVLOw?em=2&amp;wdAr=1.7777777777777777&amp;wdEaaCheck=0" width="100%" height="288px" frameborder="0">

This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.
</iframe>

:::

Перед початком вивчення програмування варто розглянути та розібрати базові поняття та категорії. Дамо визначення понять: алгоритм, задача, програмування, мова програмування, програма, програмне забезпечення, розробка програмного забезпечення.

**Програмування** – розробка програм за допомогою мов програмування.

**Мова програмування** – це формальна система знаків, що призначена для написання програм, зрозуміла для виконавця (комп’ютера).

**Програма** (`program`, `routine`) — впорядкована послідовність команд (інструкцій) комп'ютера для розв'язання задачі.

**Програмне забезпечення** (`software`) — сукупність програм обробки даних та необхідних для їх експлуатації документів. Програми призначені для машинної реалізації завдань (Задач). Терміни завдання і застосування (програма) мають дуже широке вживання в контексті інформатики і програмного забезпечення.

**Завдання** або **задача** (`problem`, `task`) — проблема, що підлягає вирішенню.

**Застосування** або **програма** (`application`) — програмна реалізація на комп'ютері рішення задачі.

**Розробка програмного забезпечення** (англ. `software engineering`, `software development`) — це рід діяльності (професія) і процес, спрямований на створення і підтримку працездатності, якості та надійності програмного забезпечення, використовуючи технології, методологію та практики з інформатики, управління проектами, математики, інженерії та інших сфер знань.

**Алгоритм** (`Algorithmi`, від імені перського математика IX ст. аль-Хорезмі) — система правил виконання обчислювального процесу, що обов'язково приводить до розв'язання певного класу задач після скінченного числа операцій. При написанні комп'ютерних програм алгоритм описує логічну послідовність операцій. Для візуального зображення алгоритмів часто використовують блок-схеми. Засоби швидкої розробки додатків (RAD) дозволяють створити програмний продукт, що складається з ряду застосувань, що дозволяють користувачам вводити дані в таблиці або редагувати вже існуючі дані, аналізувати введені дані і представляти їх у більш зручному для сприйняття вигляді - графіків, зведених таблиць або звітів (у тому числі у вигляді "паперових" документів).
